name:                aoc2019
version:             0.1.0.0
github:              "lilyrose2798/aoc2019"
license:             BSD3
author:              "Lily Rose"
maintainer:          "lilyrose2798@gmail.com"
copyright:           "2019 Lily Rose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lilyrose2798/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- split
- digits
- containers
- linear
- lens
- text
- attoparsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -XAutoDeriveTypeable
- -XBangPatterns
- -XBinaryLiterals
- -XConstraintKinds
- -XDataKinds
- -XDefaultSignatures
- -XDeriveDataTypeable
- -XDeriveFoldable
- -XDeriveFunctor
- -XDeriveGeneric
- -XDeriveTraversable
- -XDoAndIfThenElse
- -XEmptyDataDecls
- -XExistentialQuantification
- -XFlexibleContexts
- -XFlexibleInstances
- -XFunctionalDependencies
- -XGADTs
- -XGeneralizedNewtypeDeriving
- -XInstanceSigs
- -XKindSignatures
- -XLambdaCase
- -XMonadFailDesugaring
- -XMultiParamTypeClasses
- -XMultiWayIf
- -XNamedFieldPuns
- -XOverloadedStrings
- -XPartialTypeSignatures
- -XPatternGuards
- -XPolyKinds
- -XRankNTypes
- -XRecordWildCards
- -XScopedTypeVariables
- -XStandaloneDeriving
- -XTupleSections
- -XTypeFamilies
- -XTypeSynonymInstances
- -XViewPatterns

library:
  source-dirs: src/lib

executables:
  aoc2019:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
